# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    echo Hello, world!
    ls -la
  displayName: 'Run a one-line script'
  target:
   container: 867cc781-1fbd-415a-9cbf-b4277dc02168

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


resources:
  containers:
  - container: 867cc781-1fbd-415a-9cbf-b4277dc02168
    image: maven:3.6-jdk-8
 